#
# 

# https://cirrus-ci.org/guide/writing-tasks/

container:
  image: ubuntu:18.04

task:
  # doesn't work properly
  #skip: "!changesInclude('**/*.md')"
  script:
    - setup/ci_bootstrap.sh
    - make init
    - make ci test
