#
#
#  Author: Nho Luong
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/templates
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#
#

---
# https://intercom.help/hound/en/articles/2138537-flake8
flake8:
  enabled: true
  #config_file: .flake8

# http://help.houndci.com/en/articles/2138564-shellcheck
shellcheck:
  enabled: true
  #config_file: .shellcheck.yml

# http://help.houndci.com/en/articles/2138524-golint
golint:
  enabled: false

#fail_on_violations: true
