#
#
#  Author: Nho Luong
#  Date: Tue Feb 4 09:53:28 2020 +0000
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/templates
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#

build:
  nodes:
    auto:
      commands:
        # not working
        #- checkout-code ~/build
        - repo="${SCRUTINIZER_PROJECT#*/}"; git clone "https://github.com/$repo" build
        - cd ~/build
        - pwd
        - ls -l
        - make init
        - make ci test
