#
#  Author: Nho Luong
#  Date: 2020-02-23 23:30:14 +0000 (Sun, 23 Feb 2020)
#  Original: H1 2016 (Circle CI 1.x)
#
# Master Template with more advanced config:
#
#   https://github.com/nholuongut/Templates/blob/master/circleci_config.yml

# Reference:
#
#   https://circleci.com/docs/2.0/configuration-reference

version: 2.1

workflows:
  version: 2
  workflow:
    jobs:
      - build

jobs:
  build:
    docker:
      - image: cimg/base:2021.04
    resource_class: small
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.11
      - run: setup/ci_bootstrap.sh
      - run: make init
      - run: make
      - run: make test
