#
#  Author: nholuongut nho
#  Date: 2020-03-21 11:06:48 +0000 (Sat, 21 Mar 2020)
#
#

resources:
  - name: github
    icon: github-circle
    type: git
    source:
      uri: https://github.com/nholuongut/DevOps-Bash-tools
      branch: master
  #- name: daily
  #  type: time
  #  source:
  #    interval: 1d

# https://concourse-ci.org/golang-library-example.html

jobs:
  - name: build
    public: false
    plan:
      - get: github  # from resource above
        trigger: true
        #version: every  # build every git commit, default: latest
      - task: build
        config:
          platform: linux
          image_resource:
            type: docker-image
            source:
              repository: ubuntu
              tag: latest
          inputs:
            - name: github
              path: code
          params:
            CONCOURSE: 1
          run:
            path: /bin/bash
            args:
              - -c
              - |
                cd code &&
                setup/ci_bootstrap.sh &&
                make init &&
                make ci test
