#


# https://www.vagrantup.com/docs/vagrantfile

Vagrant.configure("2") do |config|

    # https://www.vagrantup.com/docs/boxes
    #
    # to get Hashicorp"s Ubuntu 18.04 base box:
    #
    # vagrant init hashicorp/bionic64
    #
    # or try one of the Bento boxes:
    #
    # https://app.vagrantup.com/bento
    #
    #config.vm.box = "hashicorp/bionic64"
    config.vm.box = "bento/ubuntu-18.04"

    # root login doesn't work on hashicorp/bionic64 or bento/ubuntu-18.04 box with pw 'vagrant'
    #config.ssh.username     = "root"
    #config.ssh.password     = "vagrant"
    config.ssh.insert_key = true
    #config.ssh.private_key_path = "~/.ssh/id_rsa"
                               # host_path         guest_path
    config.vm.synced_folder    "~/github",         "/github"
    config.vm.synced_folder    "../../",           "/bash"
    config.ssh.forward_agent = false
    config.ssh.forward_x11   = false

    config.vm.usable_port_range = 2250..2299
    #config.vm.boot_mode = "gui"

    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        #vb.name = "default-vagrant-hostname"    # overridden per VM
        vb.customize [
            "modifyvm", :id,
            "--name", "#{vb.name}",
            "--natdnsproxy1", "on",
            "--usb", "off",
            "--audio", "none"
        ]
            # using the host's DNS is simple but less portable as it requires an extra step of adding the nodes to the host's /etc/hosts file, which is an easy step to miss, so just inject the hosts files in each VM instead
            #"--natdnshostresolver1", "on",

        # evaluates too early and gets 'default-vagrant-hostname'
        #config.vm.hostname = "#{vb.name}"
    end

    # generic provision for each VM
    config.vm.provision :shell, :path => "../provision.sh"

    config.vm.define "ubuntu" do |config|
        config.vm.network "private_network", ip: "172.16.0.2"
        config.vm.provider "virtualbox" do |vb|
            # can't set vb.name at shared level, as it evaluates too early and gets 'default-vagrant-hostname'
            vb.name = "unbuntu"
            vb.cpus = 1
            vb.memory = 1024  # edit to suit your needs
            vb.customize [
                "modifyvm", :id, "--name", "#{vb.name}"
            ]
            # sets the guest OS hostname and /etc/hosts (edited by provision.sh as we want external IP and not 127.0.1.1)
            config.vm.hostname = "#{vb.name}"
        end
    end

end
