#  vim:ts=2:sts=2:sw=2:et
#

version: '2.2'

services:
  circleci:
    image: circleci/runner:launch-agent
    # or replace with an image with built-in dependencies - see https://github/nholuongut/Dockerfiles
    #image: nholuongut/circleci-runner
    environment:
      CIRCLECI_API_TOKEN: $CIRCLECI_API_TOKEN     # use the token output by the 'runner resource-class create' command above
      CIRCLECI_RESOURCE_CLASS: ${CIRCLECI_RESOURCE_CLASS:-nholuongut/docker-runner}  # <namespace>/<resource>
