#  vim:ts=2:sts=2:sw=2:et
#

version: '3'

services:
  prometheus:
    hostname: prometheus
    image: prom/prometheus:${VERSION:-latest}
    ports:
      - ${PROMETHEUS_PORT:-9090}:9090
    volumes:
      - ${PROMETHEUS_CONFIG:-./prometheus.yml}:/etc/prometheus/prometheus.yml
    #environment:
#    healthcheck:
#      # doesn't have curl
#      #test: ["CMD", "curl", "-f", "http://localhost:9090"]
#      # export DOCKER_HEALTHCHECK=/bin/true in development to bypass healthcheck
#      test: "${DOCKER_HEALTHCHECK:-curl -f http://localhost:9090}"
#      interval: 30s
#      #start_period: 30s  # version 3.4+
#      timeout: 10s
#      retries: 5
