#
#  Author: nholuongut nho
#  Date: 2016-01-17 12:56:53 +0000 (Sun, 17 Jan 2016)
#
#  vim:ts=4:sts=4:sw=4:noet

include ../Makefile.in

REPO := nholuongut/devops-bash-tools

BASH_TOOLS := ..

.PHONY: readme
readme:
	@source $(BASH_TOOLS)/.bash.d/network.sh; browser "https://github.com/$(REPO)/blob/master/.bash.d/README.md"
