#
#  Author: nholuongut nho
#  Date: Mon Nov 2 17:26:28 2015 +0000


# ============================================================================ #
#                     D o c k e r f i l e   K e y w o r d s
# ============================================================================ #


FROM
MAINTAINER
RUN
CMD
LABEL
EXPOSE
ENV
ARG
ADD
COPY
ENTRYPOINT
VOLUME
USER
WORKDIR
ONBUILD
STOPSIGNAL
HEALTHCHECK
SHELL
