#

#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/devops-bash-tools
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#

---
name: Fork Update PR

on:
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 10 * * 1'

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: false

jobs:
  fork_update_pr:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == true
    if: github.repository_owner != 'nholuongut'
    name: Fork Update PR
    uses: nholuongut/GitHub-Actions/.github/workflows/fork-update-pr.yaml@master
    with:
      debug: ${{ github.event.inputs.debug }}
