#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/devops-bash-tools
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#

---
name: JSON

on:
  push:
    branches:
      - master
      - main
    paths:
      - '**/*.json'
      - .github/workflows/json.yaml
  pull_request:
    branches:
      - master
      - main
    paths:
      - '**/*.json'
      - .github/workflows/json.yaml
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

jobs:
  check_json:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'nholuongut'
    name: Check JSON
    uses: nholuongut/GitHub-Actions/.github/workflows/json.yaml@master
    with:
      debug: ${{ github.event.inputs.debug }}
