#

#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/nholuongut/devops-bash-tools
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback
#

---
name: Trivy Docker Image Scan

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '**/*.md'
  pull_request:
    branches:
      - master
      - main
    paths-ignore:
      - '**/*.md'
  workflow_dispatch:
    inputs:
      debug:
        type: boolean
        required: false
        default: false
  schedule:
    - cron: '0 0 * * 1'

permissions:
  contents: read

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  trivy:
    # github.event.repository context not available in scheduled workflows
    #if: github.event.repository.fork == false
    if: github.repository_owner == 'nholuongut'
    name: Trivy Docker Image Scan
    uses: nholuongut/GitHub-Actions/.github/workflows/trivy.yaml@master
    with:
      docker_image: nholuongut/bash-tools
      severity: ''
